version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
      - pip install pytest
  build:
    commands:
      - echo "Running unit tests..."
      - pytest --maxfail=1 --disable-warnings -q
  post_build:
    commands:
      - echo "Build completed successfully."

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - app.py
    - requirements.txt
    - nginx/**/*
    - config/**/*